name: ORSO Val. BornAgain

on:
  push:
    branches: [ master ]
  pull_request:
  schedule:
    - cron:  '0 0 * * 1'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  validate_bornagain:
    runs-on: ubuntu-20.04
    strategy:
      max-parallel: 3

    steps:
    - uses: actions/checkout@v2

    - name: setup apt dependencies
      run: |
        sudo apt-get update

        sudo apt-get install -y --no-install-recommends python3-dev python3-pip python3-numpy python3-matplotlib

        sudo apt-get install -y --no-install-recommends build-essential \
          gfortran cmake \
          libgsl-dev libboost-all-dev libfftw3-dev libtiff5-dev libcerf-dev libeigen3-dev \
          qt5-default libqt5designercomponents5 qttools5-dev libqt5svg5-dev libqt5opengl5-dev libx11-xcb1

    - name: install own dependency LibHeinz
      run: |
        git clone https://jugit.fz-juelich.de/mlz/libheinz.git
        pushd libheinz
        mkdir build && pushd build
        cmake ..
        make
        sudo make install

    - name: install own dependency LibFormFactor
      run: |
        git clone https://jugit.fz-juelich.de/mlz/libformfactor.git
        pushd libformfactor
        mkdir build && pushd build
        cmake ..
        make
        sudo make install

    - name: Install Python packages
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install wheel setuptools
        python3 -m pip install cython pytest

    - name: Build BornAgain
      env:
        QT_QPA_PLATFORM: offscreen
      run: |
        git clone --single-branch --branch main https://jugit.fz-juelich.de/mlz/bornagain.git
        pushd bornagain
        git submodule update
        mkdir build && pushd build

        cmake -DCMAKE_INSTALL_PREFIX=/usr/local ../
        make package_source
        make -j4
        sudo make install

    - name: Validate
      run: |
        source /usr/local/bin/thisbornagain.sh
        # run validation via pytest (for Python packages)
        python -m pytest validation/scripts/test_bornagain.py
